<Project>
  <PropertyGroup>
    <!-- версия релиза: скрипт build/publish.ps1 берёт её отсюда -->
    <Version>0.1.2</Version>
    <Authors>Erney White</Authors>
    <Company>Erney White</Company>
    <Product>eViSTool</Product>
    <Copyright>© 2026 Erney White</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
